#SIGNUP USER
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "name":"Kartik",
    "email":"Kartik@gmail.com",
    "password":"12345"
}

###
#LOGIN USER
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email":"pranjalchourasia2915@gmail.com",
    "password":"12345"
}

###
#TOKEN VALIDATION
POST http://localhost:8080/api/auth/isValidToken
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNWZkMzEyNDlkNzhjYzM0ZTY4ZGRhMGM2IiwiaWF0IjoxNjA3NjY4MzAzLCJleHAiOjE2MDc2NzE5MDN9.e-PK7oIDRN58VJBuOuh0Y6CwykZc5zVo3BJDNP711VY

###
#GET ALL USERS
GET http://localhost:8080/api/user/
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNWZkMzEyNDlkNzhjYzM0ZTY4ZGRhMGM2IiwiaWF0IjoxNjA3NjY4MzAzLCJleHAiOjE2MDc2NzE5MDN9.e-PK7oIDRN58VJBuOuh0Y6CwykZc5zVo3BJDNP711VY

