#GET ALL PROJECTS
GET http://localhost:8080/api/projects
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNWZhY2RlZjY4YjdjYmExNmI4NmIwYjE3IiwiaWF0IjoxNjA1MzMyNzE4LCJleHAiOjE2MDUzMzYzMTh9.WUHgMwbKy3nxjXOAT07L9fTVC-hvvCwZaK3xUTCimuU
###
#GET ONE PROJECT
GET http://localhost:8080/api/projects/5f9bc9baa66a912adcc8152a
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNWZhY2RlZjY4YjdjYmExNmI4NmIwYjE3IiwiaWF0IjoxNjA1MzMyNzE4LCJleHAiOjE2MDUzMzYzMTh9.WUHgMwbKy3nxjXOAT07L9fTVC-hvvCwZaK3xUTCimuU
###
#ADD ONE PROJECT
POST http://localhost:8080/api/projects
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNWZkMzEyNDlkNzhjYzM0ZTY4ZGRhMGM2IiwiaWF0IjoxNjA3ODM5ODk3LCJleHAiOjE2MDc4NDM0OTd9.SvNdcCZJ8z3ivVVoLq7M9eOO8yi28eHLlofaZVLpd8M
Content-Type: application/json

{
    "title":"Project5",
    "description":"description5"
}

###
#UPDATE ONE PROJECT
PUT http://localhost:8080/api/projects/5f9bc9baa66a912adcc8152a
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNWZkMzEyNDlkNzhjYzM0ZTY4ZGRhMGM2IiwiaWF0IjoxNjA3ODcxNDg2LCJleHAiOjE2MDc4NzUwODZ9.ykvZuvkPgD7Mua6VCHGMng1Os7w0g8V92zSnvmsjtaw
Content-Type: application/json

{
    "title":"Project-1",
    "description":"description-1"
}

###
#ADD ONE TICKET
POST http://localhost:8080/api/projects/5f9bc9baa66a912adcc8152a/tickets
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNWZkMzEyNDlkNzhjYzM0ZTY4ZGRhMGM2IiwiaWF0IjoxNjA3ODcxNDg2LCJleHAiOjE2MDc4NzUwODZ9.ykvZuvkPgD7Mua6VCHGMng1Os7w0g8V92zSnvmsjtaw
Content-Type: application/json

{
    "name":"Ticket-1",
    "description":"description-1"
}